# https://taskfile.dev

version: '3'

tasks:
  libapp_so:
    cmds:
      - roc build --lib examples/hello_world/main.roc --output host/libapp.so
    sources:
      - examples/hello_world/main.roc
    generates:
      - host/libapp.so

  dynhost:
    cmds:
      - CC="zig cc" go build -C host -buildmode pie -o ../platform/dynhost
    sources:
      - host/go.mod
      - host/go.sum
      - host/main.go
      - host/main-for-surgical.go
      - "host/*/*.go"
      - host/roc/host.h
      - host/libapp.so
    generates:
      - platform/dynhost
    deps:
      - libapp_so

  preprocess:
    cmds:
      - roc preprocess-host examples/hello_world/main.roc
      - rm platform/libapp.so
    sources:
      - platform/dynhost
    generates:
      - platform/linux-x64.rh
      - platform/metadata_linux_x64.rm
    deps:
      - dynhost

  dotA:
    cmds:
      - CC="zig cc" go build -C host -buildmode c-archive -tags legacy -o ../platform/linux-x64.a
    sources:
      - host/go.mod
      - host/go.sum
      - host/main.go
      - host/main-for-surgical.go
      - "host/*/*.go"
      - host/roc/host.h
      - host/libapp.so
    generates:
      - platform/linux-x64.a

  build:
    deps:
      - preprocess
      - dotA
    
  run:
    cmds:
      - roc run --prebuilt-platform examples/hello_world/main.roc
    deps:
      - preprocess
  
  clean:
    cmds:
      - git clean -dfX
    
